#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: autogen
# autospec version: v3
# autospec commit: fae1327
#
Name     : libxcrypt
Version  : 4.4.36
Release  : 1
URL      : https://github.com/besser82/libxcrypt/archive/refs/tags/v4.4.36.tar.gz
Source0  : https://github.com/besser82/libxcrypt/archive/refs/tags/v4.4.36.tar.gz
Summary  : Extended crypt library for DES, MD5, Blowfish and others
Group    : Development/Tools
License  : LGPL-2.1
Requires: libxcrypt-lib = %{version}-%{release}
Requires: libxcrypt-license = %{version}-%{release}
Requires: libxcrypt-man = %{version}-%{release}
BuildRequires : valgrind
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
[![Build matrix](https://github.com/besser82/libxcrypt/actions/workflows/config-matrix.yml/badge.svg)](https://github.com/besser82/libxcrypt/actions/workflows/config-matrix.yml)
[![Memcheck](https://github.com/besser82/libxcrypt/actions/workflows/memcheck.yml/badge.svg)](https://github.com/besser82/libxcrypt/actions/workflows/memcheck.yml)
[![Distcheck](https://github.com/besser82/libxcrypt/actions/workflows/distcheck.yml/badge.svg)](https://github.com/besser82/libxcrypt/actions/workflows/distcheck.yml)
[![COPR Build Status](https://copr.fedorainfracloud.org/coprs/besser82/libxcrypt_CI/package/libxcrypt/status_image/last_build.png)](https://copr.fedorainfracloud.org/coprs/besser82/libxcrypt_CI)
[![codecov](https://codecov.io/gh/besser82/libxcrypt/branch/develop/graph/badge.svg)](https://codecov.io/gh/besser82/libxcrypt)
[![Coverity Scan Build Status](https://scan.coverity.com/projects/17073/badge.svg)](https://scan.coverity.com/projects/besser82-libxcrypt)
[![Codacy Badge](https://api.codacy.com/project/badge/Grade/1ebaa2314aca4bab92e14130906d5096)](https://www.codacy.com/manual/besser82/libxcrypt?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=besser82/libxcrypt&amp;utm_campaign=Badge_Grade)

%package dev
Summary: dev components for the libxcrypt package.
Group: Development
Requires: libxcrypt-lib = %{version}-%{release}
Provides: libxcrypt-devel = %{version}-%{release}
Requires: libxcrypt = %{version}-%{release}

%description dev
dev components for the libxcrypt package.


%package lib
Summary: lib components for the libxcrypt package.
Group: Libraries
Requires: libxcrypt-license = %{version}-%{release}

%description lib
lib components for the libxcrypt package.


%package license
Summary: license components for the libxcrypt package.
Group: Default

%description license
license components for the libxcrypt package.


%package man
Summary: man components for the libxcrypt package.
Group: Default

%description man
man components for the libxcrypt package.


%prep
%setup -q -n libxcrypt-4.4.36
cd %{_builddir}/libxcrypt-4.4.36

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1706812963
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%autogen --disable-static --enable-obsolete-api=glibc
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1706812963
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libxcrypt
cp %{_builddir}/libxcrypt-%{version}/COPYING.LIB %{buildroot}/usr/share/package-licenses/libxcrypt/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/crypt.h
/usr/include/xcrypt.h
/usr/lib64/libcrypt.so
/usr/lib64/libxcrypt.so
/usr/lib64/pkgconfig/libcrypt.pc
/usr/lib64/pkgconfig/libxcrypt.pc
/usr/share/man/man3/crypt.3
/usr/share/man/man3/crypt_checksalt.3
/usr/share/man/man3/crypt_gensalt.3
/usr/share/man/man3/crypt_gensalt_ra.3
/usr/share/man/man3/crypt_gensalt_rn.3
/usr/share/man/man3/crypt_preferred_method.3
/usr/share/man/man3/crypt_r.3
/usr/share/man/man3/crypt_ra.3
/usr/share/man/man3/crypt_rn.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcrypt.so.1
/usr/lib64/libcrypt.so.1.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libxcrypt/01a6b4bf79aca9b556822601186afab86e8c4fbf

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man5/crypt.5
